name: Using environment variables

on:
  workflow_dispatch:
env:
  ENV_WORKFLOW: Valor Workflow
jobs:
  test-env:
    runs-on: ubuntu-latest
    env:
      ENV_JOB: Valor test-env
    steps: 
      - name: Execução
        env:
          ENV_ACTION: Valor Action - Execução
        run:  | 
          echo: "$ENV_WORKFLOW"
          echo: "$ENV_JOB"
          echo: "$ENV_ACTION"
      
      - name: Execução 2
        env:
          ENV_ACTION: Valor Action - Execução 2
        run:  | 
          echo: "$ENV_WORKFLOW"
          echo: "$ENV_JOB"
          echo: "$ENV_ACTION"

  test-env-2:
    runs-on: ubuntu-latest
    env:
      ENV_JOB: Valor test-env-2
    steps: 
      - name: Execução
        run: | 
          echo: "$ENV_WORKFLOW"
          echo: "$ENV_JOB"
         
      
        
